import pyautogui
import time

# inicio do processo
pyautogui.hotkey('alt', 'tab')

for _ in range(2):
    pyautogui.moveTo(500, 375, duration=0.2)
    pyautogui.scroll(400)
    pyautogui.click()
    time.sleep(3)
    #seleciona o produto 1



 # inicia o processo de cadastro de tag
    pyautogui.scroll(400)
    time.sleep(0.5)
    pyautogui.moveTo(450, 375, duration=0.2)
    pyautogui.click()
    pyautogui.press('home')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('backspace')
    pyautogui.moveTo(450, 375, duration=0.2)
    pyautogui.click()
    pyautogui.click()
    pyautogui.hotkey('ctrl', 'c')
    pyautogui.press('home')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('SPACE')
    pyautogui.scroll(-4000)
    pyautogui.moveTo(450, 240, duration=0.2)
    pyautogui.click()
    pyautogui.moveTo(1100, 350, duration=0.2)
    pyautogui.click()
    pyautogui.hotkey('ctrl', 'v')
    pyautogui.press('down')
    pyautogui.press('enter')
    pyautogui.typewrite('Correia Perfil SPC')
    pyautogui.press('enter')
    pyautogui.typewrite('Correia Rexon')
    pyautogui.press('enter')
    pyautogui.typewrite('Correia em V')
    pyautogui.press('enter')
    pyautogui.press('tab')
    pyautogui.typewrite('Rexon')
    pyautogui.press('tab')
    pyautogui.typewrite('Correias em V')
    pyautogui.press('esc')
    pyautogui.moveTo(1120, 630, duration=0.2)
    time.sleep(1)
    pyautogui.click()
    time.sleep(2.5)
    pyautogui.moveTo(300, 150, duration=0.2)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(0.1)
    #finaliza a tag e volta para a página inicial

    #seleciona novo produto e faz a tag nova
    for _ in range(17):
        pyautogui.moveTo(500, 375, duration=0.2)
        pyautogui.scroll(-205)
        time.sleep(0.5)
        pyautogui.click()
        time.sleep(3)
        pyautogui.scroll(400)
        time.sleep(0.5)
        pyautogui.moveTo(450, 375, duration=0.2)
        pyautogui.click()
        pyautogui.press('home')
        pyautogui.press('Right')
        pyautogui.press('Right')
        pyautogui.press('Right')
        pyautogui.press('Right')
        pyautogui.press('backspace')
        pyautogui.moveTo(450, 375, duration=0.2)
        pyautogui.click()
        pyautogui.click()
        pyautogui.hotkey('ctrl', 'c')
        pyautogui.press('home')
        pyautogui.press('Right')
        pyautogui.press('Right')
        pyautogui.press('Right')
        pyautogui.press('SPACE')
        pyautogui.scroll(-4000)
        pyautogui.moveTo(450, 240, duration=0.2)
        pyautogui.click()
        pyautogui.moveTo(1100, 350, duration=0.2)
        pyautogui.click()
        pyautogui.hotkey('ctrl', 'v')
        pyautogui.press('down')
        pyautogui.press('enter')
        pyautogui.typewrite('Correia Perfil SPC')
        pyautogui.press('enter')
        pyautogui.typewrite('Correia Rexon')
        pyautogui.press('enter')
        pyautogui.typewrite('Correia em V')
        pyautogui.press('enter')
        pyautogui.press('tab')
        pyautogui.typewrite('Rexon')
        pyautogui.press('tab')
        pyautogui.typewrite('Correias em V')
        pyautogui.press('esc')
        pyautogui.moveTo(1120, 630, duration=0.2)
        time.sleep(1)
        pyautogui.click()
        time.sleep(2.5)
        pyautogui.moveTo(300, 150, duration=0.2)
        time.sleep(0.1)
        pyautogui.click()
        time.sleep(0.1)



    time.sleep(1)
    pyautogui.scroll(-4000)
    time.sleep(1)

    #penultimo produto

    pyautogui.moveTo(500, 430, duration=0.2)
    pyautogui.click()
    time.sleep(3)
    pyautogui.scroll(400)
    time.sleep(0.5)
    pyautogui.moveTo(450, 375, duration=0.2)
    pyautogui.click()
    pyautogui.press('home')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('backspace')
    pyautogui.moveTo(450, 375, duration=0.2)
    pyautogui.click()
    pyautogui.click()
    pyautogui.hotkey('ctrl', 'c')
    pyautogui.press('home')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('SPACE')
    pyautogui.scroll(-4000)
    pyautogui.moveTo(450, 240, duration=0.2)
    pyautogui.click()
    pyautogui.moveTo(1100, 350, duration=0.2)
    pyautogui.click()
    pyautogui.hotkey('ctrl', 'v')
    pyautogui.press('down')
    pyautogui.press('enter')
    pyautogui.typewrite('Correia Perfil SPC')
    pyautogui.press('enter')
    pyautogui.typewrite('Correia Rexon')
    pyautogui.press('enter')
    pyautogui.typewrite('Correia em V')
    pyautogui.press('enter')
    pyautogui.press('tab')
    pyautogui.typewrite('Rexon')
    pyautogui.press('tab')
    pyautogui.typewrite('Correias em V')
    pyautogui.press('esc')
    pyautogui.moveTo(1120, 630, duration=0.2)
    time.sleep(1)
    pyautogui.click()
    time.sleep(2.5)
    pyautogui.moveTo(300, 150, duration=0.2)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1)
    pyautogui.scroll(-4000)
    time.sleep(1)


    #ultimo produto
    pyautogui.moveTo(500, 500, duration=0.2)
    pyautogui.click()
    time.sleep(3)
    pyautogui.scroll(400)
    time.sleep(0.5)
    pyautogui.moveTo(450, 375, duration=0.2)
    pyautogui.click()
    pyautogui.press('home')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('backspace')
    pyautogui.moveTo(450, 375, duration=0.2)
    pyautogui.click()
    pyautogui.click()
    pyautogui.hotkey('ctrl', 'c')
    pyautogui.press('home')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('Right')
    pyautogui.press('SPACE')
    pyautogui.scroll(-4000)
    pyautogui.moveTo(450, 240, duration=0.2)
    pyautogui.click()
    pyautogui.moveTo(1100, 350, duration=0.2)
    pyautogui.click()
    pyautogui.hotkey('ctrl', 'v')
    pyautogui.press('down')
    pyautogui.press('enter')
    pyautogui.typewrite('Correia Perfil SPC')
    pyautogui.press('enter')
    pyautogui.typewrite('Correia Rexon')
    pyautogui.press('enter')
    pyautogui.typewrite('Correia em V')
    pyautogui.press('enter')
    pyautogui.press('tab')
    pyautogui.typewrite('Rexon')
    pyautogui.press('tab')
    pyautogui.typewrite('Correias em V')
    pyautogui.press('esc')
    pyautogui.moveTo(1120, 630, duration=0.2)
    time.sleep(1)
    pyautogui.click()
    time.sleep(2.5)
    pyautogui.moveTo(300, 150, duration=0.2)
    time.sleep(0.1)
    pyautogui.click()
    time.sleep(1)
    pyautogui.scroll(-4000)


    #troca de pagina
    pyautogui.moveTo(1085, 590, duration=0.2)
    pyautogui.click()
    time.sleep(2) 


